### ISSUE TITLE
Development in VisualStudio

### ISSUE THREAD

**Issue by Sri-Harsha-S** [Microchip-MPLAB-Harmony/core_apps_sam_l21#1]
Hi, This is not directly an issue but, it is less than a normal question. 

As I am very new to this type of embedded development, I want to know how to write a code for this SAML21 xplained pro board in Visual Studio.

I have searched many areas and forums even in the company website, I could not find anywhere to development that supports in visualstudio. 

Please can you guide me to install the necessary libraries those are used to write and detect the board in visualstudio?

Thank you and best regards
Sri

**Comment by aethaniel** [comment]
Hi, as far as I know there isn't any plan to support Microsoft Visual Studio.
